export var ErrorType;
(function (ErrorType) {
    ErrorType["VALIDATION_ERROR"] = "VALIDATION_ERROR";
    ErrorType["AUTHENTICATION_ERROR"] = "AUTHENTICATION_ERROR";
    ErrorType["AUTHORIZATION_ERROR"] = "AUTHORIZATION_ERROR";
    ErrorType["RATE_LIMIT_ERROR"] = "RATE_LIMIT_ERROR";
    ErrorType["SERVER_ERROR"] = "SERVER_ERROR";
    ErrorType["NETWORK_ERROR"] = "NETWORK_ERROR";
    ErrorType["SESSION_EXPIRED"] = "SESSION_EXPIRED";
    ErrorType["REFRESH_TOKEN_MISSING"] = "REFRESH_TOKEN_MISSING";
    ErrorType["REFRESH_TOKEN_INVALID"] = "REFRESH_TOKEN_INVALID";
    ErrorType["STORAGE_ERROR"] = "STORAGE_ERROR";
})(ErrorType || (ErrorType = {}));
