import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, BarChart, Bar } from 'recharts';
export function FortuneAnalysisReport({ analysis, onClose }) {
    // トレンドデータの準備
    const trendData = analysis.trends.map(trend => ({
        period: trend.period,
        confidence: trend.confidence * 100,
        trend: trend.trend === 'up' ? 1 : trend.trend === 'down' ? -1 : 0
    }));
    // パターンデータの準備
    const patternData = analysis.patterns.map(pattern => ({
        type: pattern.type,
        frequency: pattern.frequency,
        significance: pattern.significance * 100
    }));
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -20 }, className: "bg-purple-900/90 rounded-lg p-6 shadow-xl border border-purple-700/50 max-w-4xl mx-auto", children: [_jsxs("div", { className: "flex justify-between items-center mb-6", children: [_jsx("h2", { className: "text-2xl font-bold text-purple-100", children: "\u8A73\u7D30\u5206\u6790\u30EC\u30DD\u30FC\u30C8" }), onClose && (_jsx("button", { onClick: onClose, className: "text-purple-300 hover:text-purple-100 transition-colors", children: "\u2715" }))] }), _jsxs("section", { className: "mb-8", children: [_jsx("h3", { className: "text-xl font-semibold text-purple-200 mb-4", children: "\u30C8\u30EC\u30F3\u30C9\u5206\u6790" }), _jsx("div", { className: "h-64 mb-4", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(LineChart, { data: trendData, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#4B5563" }), _jsx(XAxis, { dataKey: "period", stroke: "#E9D5FF" }), _jsx(YAxis, { stroke: "#E9D5FF" }), _jsx(Tooltip, { contentStyle: {
                                            backgroundColor: '#1F2937',
                                            border: '1px solid #4B5563'
                                        } }), _jsx(Legend, {}), _jsx(Line, { type: "monotone", dataKey: "confidence", stroke: "#8B5CF6", name: "\u4FE1\u983C\u5EA6" }), _jsx(Line, { type: "monotone", dataKey: "trend", stroke: "#F472B6", name: "\u30C8\u30EC\u30F3\u30C9" })] }) }) })] }), _jsxs("section", { className: "mb-8", children: [_jsx("h3", { className: "text-xl font-semibold text-purple-200 mb-4", children: "\u30D1\u30BF\u30FC\u30F3\u5206\u6790" }), _jsx("div", { className: "h-64 mb-4", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(BarChart, { data: patternData, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#4B5563" }), _jsx(XAxis, { dataKey: "type", stroke: "#E9D5FF" }), _jsx(YAxis, { stroke: "#E9D5FF" }), _jsx(Tooltip, { contentStyle: {
                                            backgroundColor: '#1F2937',
                                            border: '1px solid #4B5563'
                                        } }), _jsx(Legend, {}), _jsx(Bar, { dataKey: "significance", fill: "#8B5CF6", name: "\u91CD\u8981\u5EA6" }), _jsx(Bar, { dataKey: "frequency", fill: "#F472B6", name: "\u983B\u5EA6" })] }) }) })] }), _jsxs("section", { className: "mb-8", children: [_jsx("h3", { className: "text-xl font-semibold text-purple-200 mb-4", children: "\u4E88\u6E2C" }), _jsx("div", { className: "space-y-4", children: analysis.predictions.map((prediction, index) => (_jsxs("div", { className: "bg-purple-800/50 rounded-lg p-4 border border-purple-700/30", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("h4", { className: "text-lg font-medium text-purple-100", children: prediction.aspect }), _jsxs("span", { className: "text-sm text-purple-300", children: ["\u78BA\u7387: ", Math.round(prediction.likelihood * 100), "%"] })] }), _jsxs("p", { className: "text-purple-200 mb-2", children: ["\u6642\u671F: ", prediction.timeframe] }), _jsxs("div", { className: "text-sm text-purple-300", children: [_jsx("p", { className: "font-medium mb-1", children: "\u6839\u62E0:" }), _jsx("ul", { className: "list-disc list-inside space-y-1", children: prediction.basis.map((basis, i) => (_jsx("li", { children: basis }, i))) })] })] }, index))) })] }), _jsxs("section", { children: [_jsx("h3", { className: "text-xl font-semibold text-purple-200 mb-4", children: "\u76F8\u95A2\u95A2\u4FC2" }), _jsx("div", { className: "space-y-4", children: analysis.correlations.map((correlation, index) => (_jsxs("div", { className: "bg-purple-800/50 rounded-lg p-4 border border-purple-700/30", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("div", { className: "text-purple-100", children: correlation.factors.join(' × ') }), _jsxs("span", { className: "text-sm text-purple-300", children: ["\u5F37\u5EA6: ", Math.round(correlation.strength * 100), "%"] })] }), _jsx("p", { className: "text-purple-200", children: correlation.description })] }, index))) })] })] }));
}
